############################生产环境################################
#
# web访问端口 约定8088
#
############################################################
server:
  port: 8088 # 指定启动端口
############################################################
#
# 配置数据源信息-服务器
#
############################################################
spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://172.17.0.13:3306/yummyfood?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: swg2020fight
############################################################
#
# mybatis 配置 生产环境不要打印每一个sql
#
############################################################
# mybatis:
  # configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql执行语句