###########################开发环境#################################
#
# web访问端口 约定8088
#
############################################################
server:
  port: 8088 # 指定启动端口
############################################################
#
# 配置数据源信息-本地
#
############################################################
spring:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/yummyfood?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql执行语句